---
title: |
  | Opinion Dynamics, Social Tipping Processes,
  | Public Opinion Change
title-meta: ""
subtitle: | 
  | *Draft Proposal: Master Thesis & PhD Project*
author: | 
  | Johann-Friedrich Salzmann [\Letter](mailto:mail@jfsalzmann.com)
  | \footnotesize Hertie School of Governance, Berlin
author-meta: Johann-Friedrich Salzmann
#date: "last edited Mar 26, 2024"
output:
  pdf_document:
    number_sections: false
    citation_package: natbib
    keep_tex: true
    df_print: kable
    latex_engine: pdflatex
    fig_caption: true
bibliography:
  - ../../../Literatur/bibtex/library.bib
urlcolor: MidnightBlue
linkcolor: MidnightBlue
citecolor: MidnightBlue
geometry: "left=1in,right=1in,top=1in,bottom=1in"
fontsize: 12pt
biblio-style: agsm
# dcu apacite
header-includes:
  - \usepackage{mathtools}
  - \usepackage{amsmath}
  - \numberwithin{equation}{section}
  - \numberwithin{table}{section}
  - \numberwithin{figure}{section}
  - \usepackage{float}
  - \usepackage{gensymb}
  - \usepackage{setspace}\singlespacing
  - \usepackage{titlesec}
  - \titlespacing*{\section}{0pt}{2cm}{0.5cm}
  - \titlespacing*{\subsection}{0pt}{1cm}{1cm}
#  - \usepackage[ngerman]{babel}
  - \usepackage[nottoc]{tocbibind}
#  - \setcounter{secnumdepth}{2}
  - \setcounter{tocdepth}{2}
  - \widowpenalties 3 10000 10000 150
  - \displaywidowpenalties 3 10000 10000 150
  - \clubpenalties 3 10000 10000 150
  - \interfootnotelinepenalty 5000
  - \raggedbottom
  - \usepackage{enumitem}
  - \setlist{itemsep=3pt,topsep=5pt,parsep=0pt,partopsep=0pt}
  - \usepackage{marvosym}
  - \usepackage{hyperref}
  - \hypersetup{bookmarksnumbered=true}
  - \usepackage{bookmark}
#  - \newcommand{\sectionbreak}{\clearpage\phantomsection}
  - \let\Begin\begin
  - \let\End\end
  - \newcommand{\Newrow}{\\}
  - \addtolength{\skip\footins}{2pc plus 5pt}
#  - \AtBeginDocument{\pdfbookmark[section]{Deckblatt}{front}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results='hide', message=FALSE, warning=FALSE)
knitr::opts_chunk$set(fig.height = 4, fig.width = 6)
options(knitr.kable.NA = '',knitr.table.format = "latex")
#knitr::read_chunk('ba.R')
library(kableExtra)
library(readxl)
library(dplyr)
```

\renewcommand{\harvardand}{\&}
\setcitestyle{authoryear,round,aysep={},notesep={: }}
\nocite{Bak-Coleman2022,Chatzilena2019,Sooknanan2016,Winkelmann2022}

### Theoretical Framework

- **Opinion Dynamics**: Opinion Diffusion, Social Contagion
- **Social Tipping Processes**/Dynamics
- **Social Movements**/Change, Collective Action
- **Public Opinion** Formation, Preference Aggregation, Spread of Misinformation

### Methodology

- **Modelling**: Compartment Models, Network Models
- **Inference**: Bayesian Generative Models
- **Causal Identification**: Causal Design (DAGs), Causal Bayesian Inference

### Implementation

- **STAN** PPL for Bayesian Inference
- **R** for Data Pre-Processing & Analysis

### Central Research Questions

- How well, and how fast, does a certain piece of information spread through a population?
- What thresholds need to be crossed so that a social tipping process of opinion diffusion takes off?
- What is the set of necessary conditions for a piece of information to be (decently) contagious?

### Working Hypotheses

- Model parameters a) can be interpreted in a meaningful way (tbd), and b) in any case, they can be compared case-to-case
- SIR-like dynamics c) underlay or d) meaningfully represent, and e) can be recovered/estimated from, real-life events


### Possible Applications / Case Studies

- Climate movement in Germany 2019 & change in MIP
- Adoption of Covid-19 social norms
- Shock induced public opinion changes: Fukushima, Brexit, Charlie Hebdo, Cologne New Year (2015) / Berlin New Year (2021), AfD 2015
- Fashion changes & trend diffusion
- Use of language (contemporary words, gender neutral expressions)

### Model Variations / Adjustments

- Repeated exposure thresholds before contagion (analogous to mass opinion formation)
- Adoption vs. immunity vs. recovery, reinfections
- Spatial or network-based transmission vs. social clusters


\footnotesize